All EIPIP Meetings/Meeting 002.md
README.md

Jim Bennett transcribed these notes.

Add Meeting 002.md and update README.md

---

All EIPIP Meetings/Meeting 004.md
README.md

Adds Call 4. Updates Readme with Call 4.
Please review and merge.

Add meeting 4

---

All EIPIP Meetings/Meeting 005.md
README.md

Add "Agenda" column to the README.md table
Re order the README.md table (most recent, first, same as all core dev calls table)

Add notes for meeting 5

---

All EIPIP Meetings/Meeting 007.md
README.md

Jim Bennett transcribed these notes.

Add Meeting 007

---

All EIPIP Meetings/Meeting 005.md
All EIPIP Meetings/Meeting 008.md
README.md

Add call 8, Update Readme

---

All EIPIP Meetings/Meeting 010.md
README.md

Add meeting 10

---

All EIPIP Meetings/Meeting 015.md
README.md

Jim Bennett Transcribed these notes.

Add Meeting 015.md and links to this and 14 in README.md

---

All EIPIP Meetings/Meeting 017.md
All EIPIP Meetings/Meeting 018.md
README.md

Fix numbering typo in Meeting 017.md
Add README.md links to 16, 17, and 18.
Jim Bennett Transcribed these notes.

Add Meeting 018.md

---

All EIPIP Meetings/Meeting 019.md

Create meeting 019.md

---

All EIPIP Meetings/Meeting 022.md

Create Meeting 022.md

---

All EIPIP Meetings/Meeting 023.md
README.md

Jim Bennett transcribed these notes.

Add Meeting 023 and links to 22 and 23 in the README.

---

All EIPIP Meetings/Meeting 026.md
README.md

feat: Add call 26

---

All EIPIP Meetings/Meeting 027.md

Create Meeting 027.md

---

All EIPIP Meetings/Meeting 028.md
README.md

Jim Bennett transcribed these notes.
and add the following links to the README.md: 24, 25, 27, and 28.

Add notes for meeting # 28

---

All EIPIP Meetings/Meeting 031.md
README.md

feat: add call 31

---

All EIPIP Meetings/Meeting 034.md

Create Meeting 034.md

---

All EIPIP Meetings/Meeting 038.md

Create Meeting 038.md

---

meeting 045.md

Create meeting 045.md

---

All EIPIP Meetings/meeting 047.md

Create meeting 047.md

---

All EIPIP Meetings/Meeting 050.md
README.md

Hi @poojaranjan . Pls review yesterdays meeting notes

Meeting Notes EIPIP50

---

All EIPIP Meetings/Meeting 048.md
All EIPIP Meetings/Meeting 049.md
README.md

@poojaranjan kindly help with Action Items and review.

Added Meeting 049.md

---

All EIPIP Meetings/Meeting 053.md
README.md

feat(53): Add meeting 53

---

All EIPIP Meetings/Meeting 054.md
README.md

EIPIP Meeting 054 and update README file

---

All EIPIP Meetings/Meeting 055.md
README.md

EIPIP Meeting 055 and Update files

---

README.md

Fix permacast link

---

All EIPIP Meetings/Meeting 061.md
README.md

Agenda: https://github.com/ethereum-cat-herders/EIPIP/issues/161

Create Meeting 61.md

---

All EIPIP Meetings/Meeting 062.md
README.md

feat: Add meeting 62

---

All EIPIP Meetings/Meeting 070.md
README.md

EIPIP Meeting 70 notes and Update README.md

---

All EIPIP Meetings/Meeting 073.md
README.md

Agenda: https://github.com/ethereum-cat-herders/EIPIP/issues/208

Meeting 073.md

---

All EIPIP Meetings/Meeting 75.md
README.md

Create meeting 75.md and updated README file 

---

All EIPIP Meetings/Meeting 078.md
README.md

Agenda: https://github.com/ethereum-cat-herders/EIPIP/issues/224

Create Meeting 078.md

---

All EIPIP Meetings/Meeting 080.md
README.md

EIPIP Meeting 080 and updated README.md 

---

All EIPIP Meetings/Meeting 083.md
README.md

Agenda: https://github.com/ethereum-cat-herders/EIPIP/issues/241

Create Meeting 083.md

---

All EIPIP Meetings/Meeting 085.md
README.md

Create Meeting 85 and Updated README.md

---

All EIPIP Meetings/Meeting 089.md
README.md

Agenda: https://github.com/ethereum-cat-herders/EIPIP/issues/260

Create Meeting 089.md

---

All EIPIP Meetings/Meeting 091.md
README.md

EIPIP Meeting 91 and Update README.md

---

All EIPIP Meetings/Meeting 092.md
README.md

Agenda: https://github.com/ethereum-cat-herders/EIPIP/issues/281

Create Meeting 092.md

---

All EIPIP Meetings/Meeting 093.md
README.md

Agenda: https://github.com/ethereum-cat-herders/EIPIP/issues/285

Create Meeting 093.md

---

All EIPIP Meetings/Meeting 094.md
README.md

EIPIP Meeting 94 

---

All EIPIP Meetings/Meeting 096.md
README.md

Create Meeting 096.md

---

All EIPIP Meetings/Meeting 095.md
README.md

Create Meeting 095.md

---

All EIPIP Meetings/Meeting 099.md
README.md

Agenda: https://github.com/ethcatherders/EIPIP/issues/310

Create Meeting 099.md

---

All EIPIP Meetings/Meeting 104.md
README.md

Agenda: https://github.com/ethcatherders/EIPIP/issues/336

Create Meeting 104.md

---

All EIPIP Meetings/Meeting 106.md
README.md

Agenda: https://github.com/ethcatherders/EIPIP/issues/340

Create Meeting 106.md

---

All EIPIP Meetings/Meeting 108.md
README.md

Agenda: https://github.com/ethcatherders/EIPIP/issues/350

Create Meeting 108.md
